# Site settings
title: Software Imagineering
email: nrcraver@gmail.com
description: > #
# baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://nickcraver.com"
twitter_username: Nick_Craver
github_username:  NickCraver
stackoverflow_link: users/13249/nick-craver

permalink: /blog/:year/:month/:day/:title/
contenturl: "/blog/content/"
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
excerpt_separator: <!--more-->

disqus: nickcraver

google_analytics_ua: UA-28897355-1

paginate: 5

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
