# Site settings
title: Software Imagineering
email: dionysius.truong@ualberta.ca
description: > #
url: "http://dt9.github.io"
twitter_username: denweny
github_username:  dt9
stackoverflow_link: users/3736384/denweny

permalink: /:categories/:year/:month/:day/:title/
contenturl: "/blog/content/"
markdown: kramdown
kramdown:
  input: GFM
  parse_block_html: true
  #parse_span_html: true
excerpt_separator: <!--more-->

disqus: dt9-github-io

google_analytics_ua: UA-85114211-1

#paginate: 5

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
