# Site settings
title: Software Imagineering
email: nrcraver@gmail.com
description: > #
# baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://nickcraver.com" # the base hostname & protocol for your site
twitter_username: Nick_Craver
github_username:  NickCraver

permalink: /:year/:month/:day/:title/
markdown: kramdown
highlighter: pygments

disqus: nickcraver

url: http://nickcraver.com

google_analytics: UA-28897355-1

paginate: 5

footer-links:
  email: nrcraver@gmail.com
  github: NickCraver
  rss: feed
  twitter: Nick_Craver
  stackoverflow: "users/13249/nick-craver"

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
